### ISSUE TITLE
Feature Request: username/password instead of device ID/local key

### ISSUE THREAD

**Issue by hebra** [apexad/eufy-robovac#14]
The way to extract the local and device ID via adb doesn't work anymore with Eufy Home 2.4+ as the JSON isn't logged anymore.

**Comment by bradydjohnson** [comment]
I second this request. I don't have an Android device to use to get the device ID.

**Comment by Olepir** [comment]
> I second this request. I don't have an Android device to use to get the device ID.

Use Android emulator

**Comment by anthonycl** [comment]
I am unable to proceed with the current instructions my device is showing offline when logged into app and logging shows nothing but:
'
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of system
--------- beginning of main

I tried the new app which shows device ID (device is still showing offline in bluestacks) but I don't see local key?

**Comment by ravredd** [comment]
I used this to get deviceid and local key.  https://gitlab.com/Rjevski/eufy-device-id-and-local-key-grabber

**Comment by treforparr** [comment]
Has anybody got the modern version of the app for latest? Eufy maybe they can copy into the dropbox with the log at done

**Comment by treforparr** [comment]
With the Logcat hack can’t get local ID or device ID

**Comment by treforparr** [comment]
I’m looking for one for my G30  model

**Comment by HenryGelderbloem** [comment]
@apexad is it possible that we could integrate the grabber tool with the Homebridge plugin so that people only have to enter their Username and Password? I think this is a huge barrier for non-tech people to use any eufy RoboVac plugin?

**Comment by apexad** [comment]
Yes, I would accept an MR. I don’t have the bandwidth to work on this plugin at the moment
