### ISSUE TITLE
No response from Robovac even with correct devID and key

### ISSUE THREAD

**Issue by victorycig** [apexad/eufy-robovac#17]
I completed all the steps correctly as far as I know, including finding the devID and key for my Robovac, but after completing the setup in Homebridge and restarting it, my Robovac only shows "no respose."

**Comment by klausbrombeere** [comment]
> I completed all the steps correctly as far as I know, including finding the devID and key for my Robovac, but after completing the setup in Homebridge and restarting it, my Robovac only shows "no respose."

I've same error and  I've Eufy RoboVac 25C, 
Homebrige v1.3.4 for Ubuntu 20.04 ARM. (Raspberry PI 2+)
Firmware Wifi : 1.1.5
Microcontroler: 1.0.1.

Debug logs:
[RoboVac] Loaded homebridge-eufy-robovac v2.1.1 child bridge successfully
Loaded 0 cached accessories from cachedAccessories.xxxx
Looking for device...
[RoboVac] RoboVac finished initializing!
Preparing Advertiser for 'RoboVac 2847' using bonjour-hap backend!
Starting to advertise 'RoboVac 2847' using bonjour-hap backend!
Homebridge v1.3.4 (RoboVac) is running on port 42819.
Looking for device...
Looking for device...
Looking for device...
Looking for device...
Looking for device...
Looking for device...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Connecting...
Robovac Error {}
Disconnected!
Found device xxxx at 192.168.1.61
Connecting...
Found device xxxx at 192.168.1.61
Connecting...
Found device xxxx at 192.168.1.61
Connecting...
Found device xxxx at 192.168.1.61
Connecting...
Found device xxxx at 192.168.1.61
Connecting...
Found device xxxx at 192.168.1.61
Connecting...
Connected!
Robovac Error {}
Disconnected!
Disconnected!
Connected!
Robovac Error {}
Disconnected!

**Comment by apexad** [comment]
This is not the repo for the homebridge plugin and that repo already has an issue open for similar issues.
https://github.com/apexad/homebridge-eufy-robovac/issues/34
