### ISSUE TITLE
Unable to get any response from terminal

### ISSUE THREAD

**Issue by spicerackk** [apexad/eufy-robovac#21]
I am following the instructions yet I am unable to get any response in terminal with any logging. 

I have the latest version of the app, I only just got my Robovac 35C yesterday, it is all configured in the app, I'm not sure if I'm doing the wrong terminal though (just using CMD on windows). 

Am i meant to be doing this in HA terminal?

**Comment by apexad** [comment]
If you are using home assistant you may want to look at https://github.com/mitchellrj/eufy_robovac instead of this one.

**Comment by apexad** [comment]
This may have also been related to #20. Either way, please re-open if you are still having issues.
