### ISSUE TITLE
API events for the vacuum bumping into objects?

### ISSUE THREAD

**Issue by davidhaas6** [apexad/eufy-robovac#27]
Does the Eufy API expose more granular info like when the vacuum bumps into an object? How would one go about adding this to your API?

**Comment by davidhaas6** [comment]
My goal is to have my vacuum shout expletives when it hits things 😈

**Comment by apexad** [comment]
See this line of the code for the reported errors:
https://github.com/apexad/eufy-robovac/blob/master/src/index.ts#L10
