### ISSUE TITLE
Feature Request: Set the fan speed

### ISSUE THREAD

**Issue by ip-rob** [apexad/eufy-robovac#30]
I noticed the plugin has a fan speed option setup, but the fan only shows up as an on/off. I am not familiar with plugin creation within this environment so I don't know how to configure the item in homebridge to allow for variable speeds. It seems if the speed can be set in the Home app, then some logic in the setCleanSpeed function like below would allow it to set the fan speed appropriately.

I'd be willing to work on the code portion if someone can suggest how to make the speed variable in the configuration.

let speeds = [[1, 34, 67], [33, 66, 100], [STANDARD, BOOST_IQ, MAX]]
for (row of speeds) {
   if (cleanSpeed >= row[0] && cleanSpeed <= row[1]) {
      await this.doWork(async () => {
            await this.set({
                [this.CLEAN_SPEED]: row[2]
            })
        });
   }
}

**Comment by apexad** [comment]
ios 18 has native vacuum support now so if this plugin is ever updated this issue is now irrelevant.
