### ISSUE TITLE
Eufy G30 hybrid 

### ISSUE THREAD

**Issue by damitch300** [apexad/eufy-robovac#33]
Hello there,

The G30 Hybrid doesnt work with the old Eufy app, so i cant get the key and localid from the app there.
So i tried to use ADB on my W11. I did manage to get the ID but the key seems to not come up.
What i do get is [fetchEncodeKey:65]: md5 key len:16   (and a few others).

Do you have any idea what i can do to continue?

**Comment by lkucera** [comment]
> Hello there,
> 
> The G30 Hybrid doesnt work with the old Eufy app, so i cant get the key and localid from the app there. So i tried to use ADB on my W11. I did manage to get the ID but the key seems to not come up. What i do get is [fetchEncodeKey:65]: md5 key len:16 (and a few others).
> 
> Do you have any idea what i can do to continue?

same issue, none of G30 seems to work with old app, so far I didn't figured out how to get the keys... :(
